### ISSUE TITLE
Quick question: Is ELKS real-time OS?

### ISSUE THREAD

**Issue by toncho11** [ghaerr/elks#1154]
Hi,

Can ELKS be considered real-time OS? Usually that depends on the kernel scheduler.

Still the kernel code is small (compared to regular Linux) and there are not many processes running when the system boots up. So in general it should be pretty responsive, even "real-time" ?

**Comment by Mellvik** [comment]
Hi @toncho11,
I'm sure @ghaerr will elaborate on this, but ELKS is definitely not a real time OS. There is no guarantee that an interrupt or a process will be serviced within a certain time frame. And - since ELKS is using BIOS-services for a number of tasks (such as floppy and disk I/O), real time is off the table.

There have been many discussions about the benefits and drawbacks of this BIOS dependability over the years, and the conclusion has always been (this far) that the portability provided by the BIOS, which is 'hiding' peculiarities of the actual system from the OS, is extremely attractive. 

--M

**Comment by toncho11** [comment]
And BIOS adds a considerable unpredictable delay?

**Comment by Mellvik** [comment]
'Unpredictable' yes, 'considerable' – you never know because it's unpredictable.

The thing is, you don't control interrupts when handing over control to the BIOS. And you never know how the BIOS does things. There are thousands of them, all different on the inside, (almost) alike on the outside (API).

-M

**Comment by toncho11** [comment]
Interesting. I always thought the BIOS interrupts are rather short segments of code that should not take too much time. But then even back then developers preferred to access the hardware directly (graphics for example).

**Comment by ghaerr** [comment]
Hello @toncho11,

> I always thought the BIOS interrupts are rather short segments of code that should not take too much time.

Not when calling BIOS to do floppy disk I/O! But there are many others that could take milliseconds instead of seconds, which are not suitable for any real time operation.

> Can ELKS be considered real-time OS? Usually that depends on the kernel scheduler.

Adding to all that @Mellvik has said, which I agree with, the definition of "real time OS" means that the scheduler can schedule a task to run at an absolute known time (e.g. every 10ms no matter what), which is fundamentally different than a scheduler that say, schedules a task to run "high priority" and always switches to it before any other task.

The point that @Mellvik is making about ELKS using the system BIOS is that the kernel loses control (possibly completely if interrupts are turned off within, for instance) when calling any BIOS function. Because of that, scheduling in real time is not possible.

> there are not many processes running when the system boots up. So in general it should be pretty responsive

I think "very" responsive. ELKS is limited to 16 processes, and uses the clock interrupt (every 1/100 second) to check whether the next task should run. If the clock interrupts when an application is running (but not in the kernel), then ELKS attempts to run the next task in line for 1/100 second. If the interrupted application is in the middle of an ELKS system call, then a task switch is not performed, as the kernel is not reentrant, and the timer interrupt returns control back to the interrupted kernel code.

There is currently no priority in scheduling, ELKS uses what's called "round robin" which means going from one task to the next in a chain, repeatedly. When there are no tasks to run at all, the "idle" task is run, which recently was enhanced to sync the filesystems every so many seconds, if configured.

Thank you!

**Comment by toncho11** [comment]
But if it is on a fast CPU you can set it to 5ms to switch between tasks instead of currently 10?

OK. I see:
- BIOS interrupts that can take long time
- slow switching between tasks
- no priorities in the kernel

I was thinking for some real world use of ELKS when combined with some hardware like for example drone control over wifi using this board: [FabGL ESP32 board](https://www.youtube.com/watch?v=O9AP4vZHfjI&ab_channel=FabrizioDiVittorio) that has an IBM PC emulator.

**Comment by ssieb** [comment]
If you have an ESP32, it already comes with an RTOS.  Why slow it down with an emulator?
