### ISSUE TITLE
Does not show anything with ps command

### ISSUE THREAD

**Issue by tyama501** [ghaerr/elks#1436]
Hello,

![ps](https://user-images.githubusercontent.com/61556504/188502416-80795b60-e211-4c71-9b95-a8cb54c0e28d.png)

It seems the ps commad does not show anything on 02 Sep build.
Did it change something recently?

**Comment by toncho11** [comment]
It should show `init`, `sh` and `ps` ?

**Comment by ghaerr** [comment]
Hello @tyama501,

I just tested this and `ps` works fine for me (using CONFIG_ARCH_IBMPC). Are you saying that the image built for PC-98 (fd1232.img) via Github Contiguous Integration contains a non-working `ps`? If so, please try building from scratch on your own system and lets see what happens.

Thank you!

**Comment by tyama501** [comment]
Thank you.

〉Are you saying that the image built for PC-98 (fd1232.img) via Github Contiguous Integration

Yes, I just wrote how to get the newest image in the document and found this.

I will try my build later.

**Comment by ghaerr** [comment]
> Are you saying that the image built for PC-98 (fd1232.img) via Github Contiguous Integration
> Yes, I just wrote how to get the newest image in the document and found this.

I suspect the problem is that `ps` is dependent on the internal structure of the `task_struct` array of the kernel, and reads it using /dev/kmem. The issue is likely that CONFIG_CPU_USAGE is not set the same for the kernel and ps.c compilations, thus causing the task_struct to not match. (I will have to check, but am wondering whether CONFIG_CPU_USAGE is set for a default kernel build - I know it is set for the pc98-1232.config build). 

This could probably be fixed by adding the following line in `build.sh`:
```
# Build PC-98 kernel, some user land files and image
if [ "$1" = "auto" ]; then
    echo "Building PC-98 image..."
    cp pc98-1232.config .config
    make kclean || clean_exit 9
    rm elkscmd/sys_utils/clock.o
    rm elkscmd/sys_utils/ps.o    # <-- add this line
    rm elkscmd/basic/*.o
    rm elkscmd/nano-X/*.o
    make -j1 || clean_exit 10
fi
```
I have been working towards not requiring that ELKS applications have to be built using any kernel options, but there are a few exceptions, namely `clock`, `ps`, `basic` and `nano-X`. In this case, it would be preferable to have CONFIG_CPU_USAGE turned on by default; that wasn't done because it uses another 5 words per task, which I suppose is no big deal. 

I'll post the above fix and see whether that works, then consider the CONFIG_CPU_USAGE issue.

**Comment by tyama501** [comment]
I built from the latest commit and yes it worked.

![ps2](https://user-images.githubusercontent.com/61556504/188710193-0ccb507d-c86a-4514-b8fc-d10bf3ecf4d7.png)

Thank you.

**Comment by tyama501** [comment]
Thank you!
