### ISSUE TITLE
Buildsystem does not like -j N

### ISSUE THREAD

**Issue by Randrianasulu** [ghaerr/elks#1565]
I think attempt at using make's parallel build feature result in build error.

Try 'make -j 8' in elks directory - it will stop in bc directory for example.

 make --version                                                
GNU Make 4.3                                                                                     
Built for i586-slackware-linux-gnu

**Comment by ghaerr** [comment]
I suppose I am not surprised... the source base is 20+ years old, and many of the ELKS application Makefiles do not list all of the dependencies required. There is not a project-wide 'make depend' either. Due to the complexities of getting this to work with the special interdependencies of the ELKS C library and the toolchain, getting this working is pretty low on the priority list, however, contributions welcome.
