### ISSUE TITLE
Congratulations and wish list for elks functionality

### ISSUE THREAD

**Issue by djohanse** [ghaerr/elks#1788]
It's been a few years since I looked at elks.  Congratulations on all the progress!

My wishlist.  Things I think would add value to elks.

1. Support or the following commands:
    ifconfig
    ping
    whoami

2. Networking support for UDP

**Comment by ghaerr** [comment]
Hello @djohanse,

Thanks! 

Sounds like you've already run into `netstat`, which gives some network information similar to `ifconfig`.  Currently, the network is configured using the `/bin/net` shell script which essentially reads `/etc/net.cfg`. For a variety of reasons, it'll probably stay that way, rather than building functionality into an `ifconfig`-like executable.

`ping` is already on my list, porting a typical ping.c source needs a bit more work as our TCP/IP stack doesn't really have much of an ICMP layer and we need some method of communicating the ICMP request with `ktcp`, which doesn't yet exist.

`whoami` probably won't be ported as ELKS doesn't use /var/utmp in order to keep library and application sizes down, likely because most folks don't run multiuser logins. There is the capability to turn on UTMP in various applications and elkscmd/sys_utils/who.c could easily be enhanced to support `who am i`. 

Finally, yes, UDP would be great :) Our TCP/IP stack doesn't have any UDP layer currently, this would be a bigger project. What applications do you have in mind that require UDP?

Contributions welcome :)

Thank you!
