### ISSUE TITLE
Not an issue, but i am willing to donate the intel etherexpress 8/16 network card

### ISSUE THREAD

**Issue by sparky4** [ghaerr/elks#1797]
i am willing to donate a card straight from ebay ^^
i just need an address.
Please contact me with address via email to sparky4 <> johnreedcenter.net
ill pay for everything

**Comment by ghaerr** [comment]
Hello @Mellvik, are you interested in this? I realize TLVC isn't totally compatible with ELKS but it would be nice to work towards driver compatibility between the two (and I have some ideas on that), and you're the network/NIC expert. I haven't yet been able to get a NIC working in my desktop 386 or I'd take this on myself.

**Comment by Mellvik** [comment]
Thanks for bringing this to my attention, @ghaerr. 
Not knowing anything about the Intel NIC, I'll have to come back to the actual offer after looking into it and evaluating the effort. Insatiable curiosity is a blessing and a curse, and I'll admit it sounds tempting.
As to NIC driver compatibility between ELKS and TLVC, I don't know what has changed in ELKS since the fork. If it's minimal, it should be 'low threshold'. 
Getting the 386 desktop networked - contact me out-of-band.

-M

**Comment by sparky4** [comment]
here is the source code of the packet driver let me test it http://crynwr.com/drivers/exp16118.zip

**Comment by ccoffing** [comment]
FWIW I also have several Intel EE 8/16 sitting around that I want to use in ELKS.  I am no networking guru, but if this effort gets started, I can help test.

**Comment by Mellvik** [comment]
Thanks Chuck, that will be very useful.

The ‘project’ will commence when the NIC arrives from sparky4 - some time in March.
FYI the development will be on [TLVC](https://github.com/Mellvik/TLVC), not ELKS, but the result will presumably be a simple drop-in for ELKS.

**Comment by sparky4** [comment]
ill send it out today

**Comment by sparky4** [comment]
did ya get the part?

**Comment by Mellvik** [comment]
Hi @sparky4 - I'm following the tracker,
2 weeks in florida, seems to be on its way now... will letyoy know when it arrives.

**Comment by sparky4** [comment]
info any info on integration of the card drivers into elks?

**Comment by Mellvik** [comment]
@ghaerr, if you merge the sources into ELKS, I can do the testing. 

The structure of the driver is 'old style', passing data directly to/from ktcp. Look at PR #60 for details, there is no man page. The driver supports shared memory and PIO, the latter is the default, the former is slightly faster. It takes hardware config from /bootopts if available. SHmem is compile time configurable. I haven't used this interface for quite some time so I'm a bit rusty. The current version is quite fast IIRC, on par with the fastest we have on ELKS/TLVC.

**Comment by ghaerr** [comment]
> if you merge the sources into ELKS, I can do the testing.

Do you mean port the sources from TLVC, or merge as in you've got a PR or patch file ready? I'm aware we've been talking about designing a common driver API that would allow for NIC drivers (and eventually block device drivers) to be shared between ELKS and TLVC, but I'm not aware anything has become of it. I would do the design, but suffer from not being able to (easily) test any but the NE2K NIC driver due to poor or nonexistent NIC emulations in most all emulators. Almost the entirely of all my ELKS enhancements over the past five years has used emulators for development and testing.

> It takes hardware config from /bootopts if available

I don't want to break ELKS networking by adding code I can't test, and I'm pretty sure the configuration portion of the differing APIs aren't compatible. "Drop in" drivers will require that configuration be implemented in the driver source amongst other things, not outside like is currently done in init/main.c using global variables, etc.

> The structure of the driver is 'old style'

> The current version is quite fast IIRC

I'm guessing that means it doesn't matter that much whether the driver is new or old style, since its very fast.

> FYI the development will be on [TLVC](https://github.com/Mellvik/TLVC), not ELKS, but the result will presumably be a simple drop-in for ELKS.

@sparky4, I would suggest you run @Mellvik's fork for testing. He can say whether we have a drop-in replacement for ELKS, but my guess is not yet.

**Comment by Mellvik** [comment]
@ghaerr, I'm not following ELKS regularly and I was unaware of the new 'rules of engagement'. What I'm reading from your post is 

- No contributions, everything has to come from you
- Nothing is of interest unless you can test it yourself, which presumably means QEMU

Surprising but good to know. 

For the record, getting the ee16 driver set up in ELKS alongside the other ethernet drivers would take you less than 10 minutes. Also, given that it's a CONFIGURE-able driver, it's hard to see what it could possibly break.

**Comment by ghaerr** [comment]
> No contributions, everything has to come from you

No @Mellvik, ELKS regularly receives interesting contributions that are reviewed and committed.

> Nothing is of interest unless you can test it yourself, which presumably means QEMU

If a contribution can't be tested on one of the emulators I can run (e.g. QEMU, pcem, MartyPC, bochs, emu86) then I ask the contributor to test before commit. This is to keep the quality of ELKS high and bug reports low.

> For the record, getting the ee16 driver set up in ELKS alongside the other ethernet drivers would take you less than 10 minutes. Also, given that it's a CONFIGURE-able driver, it's hard to see what it could possibly break.

Great, can you please post a PR or patch?

**Comment by sparky4** [comment]
> [@sparky4](https://github.com/sparky4), I would suggest you run [@Mellvik](https://github.com/Mellvik)'s fork for testing. He can say whether we have a drop-in replacement for ELKS, but my guess is not yet.


link me the code <3

**Comment by sparky4** [comment]
> For the record, getting the ee16 driver set up in ELKS alongside the other ethernet drivers would take you less than 10 minutes. Also, given that it's a CONFIGURE-able driver, it's hard to see what it could possibly break.

how do i do this?

**Comment by ghaerr** [comment]
@sparky4: do you have an identical NIC on your system like you sent @Mellvik? If so, compile up a copy of TLVC and boot it on your system and test it. When we you have it working on your system, I can then help more, since I am unable to test that card on my end.

**Comment by sparky4** [comment]
Doing that now

**Comment by Mellvik** [comment]
@sparky4 - please post an issue on TLVC if you have questions or run into issues. You may actually be better off running TLVC than ELKS unless you need some of the special features - like graphics, games, alternative development tools and more. TLVC is better on drivers, networking, serial, configuration and OS oriented tooling.

**Comment by sparky4** [comment]
cool! will do
