### ISSUE TITLE
[qemu] cannot get network up

### ISSUE THREAD

**Issue by floriangit** [ghaerr/elks#1814]
Following the WIKI `Networking with QEMU` I attempted to use networking on qemu with its host.
Following a `net start` within qemu, I get:

![screen](https://github.com/ghaerr/elks/assets/90066055/5d96f689-a2d2-43c6-a6c4-d40c3d4d54d5)

What could be wrong?
On a similar note, would it make sense that ping is ported to ELKS?

**Comment by ghaerr** [comment]
> Following a net start within qemu, I get:
> What could be wrong?

It's likely that QEMU thinks that there is no NIC in the ELKS kernel configured location for it. In order to debug this, we need to see the startup screen where the various network devices are probed and identified as found or not. Something like:
<img width="832" alt="net devices" src="https://github.com/ghaerr/elks/assets/11985637/af0dda60-fd12-402c-b546-ac742e23a587">
The three lines `eth:` above show that ne0 was identified as present. It is also possible that your configuration does not include networking. I think the QEMU default for ne2000 is address 0x300 IRQ 12.

**Comment by floriangit** [comment]
Thanks for your pointers. With those I first looked at my kernel config (git default) and `NE2K` was unset there. So I rebuilt with `NE2K` enabled and I can enable the network now successfully within QEMU. Should `NE2K` be a default config?
Also, why are we setting QEMU in /bootopts as well as in /etc/net.cfg ?

I still don't have any success with `telnet 10.0.2.15 2323` or `ftp 10.0.2.15 8021` as per the WIKI, but that's a task for another day ...

**Comment by ghaerr** [comment]
> Should NE2K be a default config?

Networking is enabled by default config `ibmpc-1440.config`, which is used for release versions. Are you using something different?

> Also, why are we setting QEMU in /bootopts as well as in /etc/net.cfg ?

I suppose it is easier to set in /bootopts, but the option left in /etc/net.cfg as a reminder that `ftpd` doesn't work well on QEMU unless set. This option enables some special handling which we should get rid of somehow at some point. 

I just learned about a possible automatic mechanism to detect if running on QEMU, I've added that to my list to check out further.

> I still don't have any success with telnet 10.0.2.15 2323 or ftp 10.0.2.15 8021 as per the WIKI, but that's a task for another day ...

Unfortunately QEMU network setup can get complicated due to IP forwarding and other tricks. See the `FWD=` line in `qemu.sh`. You might also try connecting out from ELKS instead of into it, sometimes that works easier.

**Comment by floriangit** [comment]
> Networking is enabled by default config ibmpc-1440.config, which is used for release versions. Are you using something different?

I was somehow assuming since I did not have anything relevant shown in `git status` that my config is also unchanged. However, looking at it I see now only the default options being version controlled (of course that makes sense!). It may likely be that I turned off NE2K support in the kernel config long time ago when I deployed ELKS on my 286-PC first time.
IOW: user error :)

**Comment by floriangit** [comment]
To follow up on this, today I tried on a different machine with a fresh clone:

`cd /tmp`
`git clone https://github.com/ghaerr/elks.git`
`cd elks`
`. env.sh`
`make menuconfig (just save & exit there)`
`grep NE2K .config`
`# CONFIG_ETH_NE2K is not set`

**Comment by ghaerr** [comment]
>  I tried on a different machine with a fresh clone

Got it. This has been fixed in #1816, thanks!
