### ISSUE TITLE
Add automatic user feedback ?

### ISSUE THREAD

**Issue by mfld-fr** [ghaerr/elks#224]
What about adding a feedback in the configuration & build script ? Activated after the explicit consent of the user, it would upload some anonymous data to one of our server, like the ELKS configuration, in order to help us to figure out what is the real usage of the product and where we should focus our effort ?

**Comment by jbruchon** [comment]
People are likely to use the default configuration in the vast majority of cases and I don't think the config file will tell us much unless they're having an issue and want to report it.

Why not just ask them at the end of building to send in feedback and participate? They can post here, the mailing list, or just email it straight to me and I can proxy post it to the mailing list since it's grouchy about being sent HTML emails.

**Comment by Mellvik** [comment]
I like this idea and agree that the config file may not be very useful - although for a different reason: I can go through 10 config files in an hour in order to test something, and I switch between configs all the time, since networking doesn't go with FAT fs.

Having a venue for comments and feedback would be very welcome.

**Comment by mfld-fr** [comment]
No more willing to setup a server in my cloud for that feedback. Closing my proposal.
