### ISSUE TITLE
Release 0.3.1 draft

### ISSUE THREAD

**Issue by mfld-fr** [ghaerr/elks#307]
Release criteria:
- All reported boot problems on real HW solved (see mailing list)
- FAT support proven to be dramatically improved (TBC by @Mellvik on real HW)
- Images from package manager as artifacts in the CI
- Boot from FAT

Draft of the release description:

Main changes (thanks @ghaerr) :
- Build under OSX
- Build as normal user (no more `sudo`)
- Nano-X graphics restored and integrated
- MINIX filesystem tools on host side
- FATimages support (FD and flat HD only)
- Boot from FAT volume
- ELKSEMU take over and fixing (thanks @tkchia)

Minor changes:
- GCC-IA16 usage (thanks @tkchia)
- LIBC tuning (thanks @tkchia)
- `chmem` tool reintroduced on target
- ELKS BPB for easier FD CHS probing
- Safer wait event function
- Kernel code cleanup
- Ram disk restored

Bug fixes:
- Configuration & build scripts (thanks @tkchia)
- Kernel FAT filesystem and FAT fake `dev` (thanks @fonin and @ghaerr)

Milestone: https://github.com/elks-org/elks/milestone/1

**Comment by Mellvik** [comment]
Great work everyone,
I'll do some physical hardware testing (80286/12 and 80386/20) over the weekend. Which configuration(s) should I be focusing on?

Mellvik

**Comment by mfld-fr** [comment]
It would be nice if we could kill issues #123 and #306.

So I would say booting from a MINIX floppy, mounting the FAT HD and try to reproduce 🤔 ?

**Comment by ghaerr** [comment]
@Mellvik:

> So I would say booting from a MINIX floppy, mounting the FAT HD and try to reproduce 🤔 ?

Agreed.  I will temporarily modify /etc/rc.d/rc.sysinit to try mounting FAT from /dev/fd1 rather than /dev/bda1 which will greatly speed up your testing by not having to mount -t msdos /dev/fd1 /mnt after every boot. I am very interested in bug reports that can be confirmed with commands immediately after boot, although I realize that some #123 issues are stubborn and require more time and not easily reproducible.

I have only been testing on on the 1440k floppy (fd1440-fat.bin) on QEMU, so it would be nice to also test 360k and 720k images if possible (although no big deal, since they're all FAT12 at this point). The FAT16 and FAT32 testing require larger disk images than we have on older equipment, so that will likely be tested on an emulator, right?

**Comment by xrayer** [comment]
Wow, I can see "Boot from FAT", well what bootsector code did you implemented and how problem with /dev was solved? I will update the sources, recomplile and try out on my 286  :)

**Comment by mfld-fr** [comment]
@xrayer : thank you to be so enthusiast ! But this issue is only to draft the next release. Please wait a bit more to get that next release published 😄 ...

For the explanations about /dev handling and boot sector, please see the ongoing discussion in #296.

**Comment by xrayer** [comment]
(Moved to #324)

**Comment by mfld-fr** [comment]
Not managing the next release anymore. Closing this one.
