### ISSUE TITLE
Testing chmem

### ISSUE THREAD

**Issue by georgp24** [ghaerr/elks#658]
Since I have trouble with Kilo and memory allocation and while testing observed some things I could not understand I did some additional tests with the `checkmem.c` test program:
```
/* compile with:
 * ia16-elf-gcc checkmem.c -o checkmem -melks-libc -mcmodel=small
 * cp ./checkmem elkscmd/rootfs_template/bin
 * make
 * ./qemu.sh
 */
#include <stdlib.h>
#include <stdio.h>
void *r[64];
int checkAvailableMemory()
{
    int Kb = 0;
    int i = 0;
    for (i=0; i<64; i++) {
        r[i]=malloc(1024);
        if (r[i] != NULL) {
            Kb++;
            printf("Allocated %d Kb total, returned memory address from malloc=%x\r\n", Kb,r[i]);
        } else {
            printf("NULL pointer received - terminating\r\n");
            break;
        }
    }
    for (int j=0;j<i;j++) free(r[j]);
    return Kb;
}
int main() {
    int Kb = 0;
    Kb = checkAvailableMemory();
    printf("Allocated %d Kb total\n",Kb);
    return 0;
} 
```
First I compile this program with the command line:
`ia16-elf-gcc checkmem.c -o checkmem -melks-libc -mcmodel=small`
This allows just to allocate 3 Kb of memory:
![checkmem20](https://user-images.githubusercontent.com/10487642/83965488-6462d600-a8b4-11ea-80d0-cf764bbdf735.png)
So I tried to increase the heap with `chmem`:
![checkmem24](https://user-images.githubusercontent.com/10487642/83965550-ba377e00-a8b4-11ea-8786-26d6b37bef29.png)
Is it correct that the default stack size is zero? I specified the heap size as 70,000 bytes assuming `chmem` would truncate to the correct size as it did in the past. However, it did not do that, it accepts a heap of 70,000 bytes. So I tried a heap size of 64,000 and `chmem` truncated this to 57,728 bytes. However, when I add 512 bytes stack, it truncates to 61,312 bytes, so gives me more heap than without stack. When I run the `checkmem` program now it allows to allocate 59 Kbyte:
![checkmem25](https://user-images.githubusercontent.com/10487642/83965675-9d4f7a80-a8b5-11ea-8e95-e1c57d9d281f.png)
Now I tried the new `-maout-heap` parameter. If I specify `-maout-heap=0xFFFF` I can allocate 55 Kb:
![checkmem28](https://user-images.githubusercontent.com/10487642/83965738-3aaaae80-a8b6-11ea-837a-b78f6de6a914.png)
This is unexpected because I could allocate 59 Kb using `chmem` with a smaller heap size above. When I add the `-maout-stack=2048` parameter I can allocate more then 55 Kb, its 57 KB then.
![checkmem29](https://user-images.githubusercontent.com/10487642/83965973-d2f56300-a8b7-11ea-9040-6a111d3013ea.png)
However, when I enter the `-maout-heap=60000 -maout-stack=2048` parameters I get the message `file memory too large`:
![checkmem30](https://user-images.githubusercontent.com/10487642/83965823-ae4cbb80-a8b6-11ea-89e7-a3f8bc631470.png)
So `ia16-elf-gcc` does not truncate the heap to a valid size like chmem does.

**Comment by ghaerr** [comment]
Georg,

First, the values shown in the HEAP and STACK fields are normally the values that are in the a.out heap and minstack fields on disk. When 0, that means the default of 4k (each) is used. The TOTDATA field is the sum of DATA+BSS+heap+stack, where heap and stack = 0 means use 4k. In any case, passing values > 64k (like 70000) is meaningless and should not be used. I had thought I set an error for that case, so this is a bug in display only. You'll notice that if you run chmem again after setting 70000, it will show a value of HEAP of 4464, which is 70000-65536.

> So I tried a heap size of 64,000 and chmem truncated this to 57,728 bytes. However, when I add 512 bytes stack, it truncates to 61,312 bytes, so gives me more heap than without stack. 

When you say "without a stack", that is never the case. 0 means use the default (4k) stack size. The reason that 0 was implemented for heap and stack is that otherwise, one would have to specify a heap and stack for every program, so the a.out header is set to 0/0 for heap and stack by default. When you specify 512 byte stack, that removes another 3.5k bytes from the stack, which then allows a larger heap, which is handled correctly.

> However, when I enter the -maout-heap=60000 -maout-stack=2048 parameters I get the message file memory too large:

The reason for this is that it was decided by @tkchia and I that the compiler would not interpret the values passed to -maout-heap= and -maout-stack=, unlike how chmem operates. The reasons for this are kind of complicated, and discussed under the various PRs made by myself and the compiler when implementing per-process stack/heap. An additional reason is that the compiler is no longer using a linker script to create the a.out header as it was in the past, and we didn't want to include the ELKS chmem logic inside the compiler.

The proper method for setting the compiler heap/stack values is to either use -maout-heap=0xffff, which means "allocate max heap", or to tune the program by taking a careful inspection of its stack usage by looking at the source code, and then using chmem in real time to see which heap (other than max) works best for the problem, and then pass the displayed chmem HEAP value to the compiler. There's extra logic in chmem that may be updated over time that is intended to help in process memory allocation tuning.
