### ISSUE TITLE
Problem with boot after cp folder

### ISSUE THREAD

**Issue by toncho11** [ghaerr/elks#853]
Using hdd with fat16 partition after sys tool.

After successful boot from hdd I do:

```
mount -t msdos /dev/fd0 /mnt
cp /mnt/bin/* /bin/
```

end then I reboot. 
After that ELKS does not complete the boot process. It stops after "Mounted root 0x0301 (msdos filesystem)"

If I copy single file it is ok - it boots.
The problem seem to be only when the entire folder is copied.
After the entire folder is copied - programs appear to be working (before reboot)
The problem comes after rebooting and after that the system is unusable.

I also tried:

```
$ sudo fsck.vfat -w -a /dev/sdb1
fsck.fat 4.1 (2017-01-24)
FATs differ but appear to be intact. Using first FAT.
Performing changes.
/dev/sdb1: 36 files, 61/35117 clusters
```
and this did not help. Still unbootable.

Windows is able to read and write to this fat16, even if ELKS does not boot completely.

**Comment by ghaerr** [comment]
Try erasing /bin/init on the new system. I'm betting the system is trying to run init without the appropriate /etc/inittab files, etc.

**Comment by toncho11** [comment]
Yes. That was the problem. 
So maybe the sys tool can have a "-F" option that copies everything including the /etc folder.

**Comment by ghaerr** [comment]
> So maybe the sys tool can have a "-F" option that copies everything including the /etc folder.

Yes, although -F could fail from a hard disk to a smaller floppy. I need to think about what an ELKS "system" is in terms of all the extra files, and whether or not the sys command should be in the business of copying full disk images. Agreed it should be made simple.

However, probably wait until we have a recursive copy command (cp -R), so that the sys script doesn't need to be updated depending on what happens to be in /etc, /bin, etc. Perhaps a cp -Rn that copies everything but doesn't overwrite anything already existing on the destination, would be preferable, then just executing that after sys.
