### ISSUE TITLE
Support for HP Jornada and similar devices, running DOS emulators?

### ISSUE THREAD

**Issue by theshinyknight** [ghaerr/elks#978]
Would be great to run ELKS on those ARM-based handheld pc. which can run DOS emulation to emulate 8088 and 8086.

Is there any plan to support such devices? Teh DOS emulator on the Jornada is able to use img files for the floppies

**Comment by ghaerr** [comment]
Hello @theshinyknight,

Thanks for your interest in ELKS! 

There isn't any plan to directly support the Jornada, for which would require lots of work as it would require a full port to a new processor, a new toolchain, lots of ASM routine recoding, and all new timer, irq controller, console and keyboard drivers.

However, using your idea of running a DOS emulation could work, provided that the DOS emulation fully emulated the PC hardware and BIOS as well. Almost all the work would be with the DOS emulator, outside of the ELKS project. I suspect, given that the Jornada device(s) seem to support WinCE that the DOS emulator is mostly emulating the software DOS calls and 8086 CPU, rather than emulating a full PC hardware environment, which would be required for ELKS to book without modification.

Thank you!
